name: Testing (Pull Request)
on:
  pull_request
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: check out code
        uses: actions/checkout@v3
      - name: install
        run: yarn
      - name: unit tests
        run: yarn test:coverage
        env:
          CI: true
      - name: upload test coverage to codecov
        uses: codecov/codecov-action@v3
